CREATE TABLE IF NOT EXISTS compilation_accessings
(
    compilation_accessing_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (compilation_accessing_id)
);

CREATE TABLE IF NOT EXISTS detailed_event_accessing
(
    detailed_event_accessing_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (detailed_event_accessing_id)
);