CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(512) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS application_states
(
    application_state_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state                VARCHAR(255)                            NOT NULL,
    PRIMARY KEY (application_state_id)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS publication_states
(
    publication_state_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state VARCHAR(255) NOT NULL,
    PRIMARY KEY (publication_state_id)
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat         real                                    NOT NULL,
    lon         real                                    NOT NULL,
    PRiMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE            NOT NULL,
    annotation         VARCHAR(512)                                              NOT NULL,
    category           int REFERENCES categories (category_id)                   NOT NULL,
    confirmedRequests  int                                                       NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE                               NOT NULL,
    description        VARCHAR(512)                                              NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                               NOT NULL,
    initiator          int REFERENCES users (user_id),
    location           int REFERENCES locations (location_id),
    paid               boolean                                                   NOT NULL,
    participantLimit   int                                                       NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE                               NOT NULL,
    request_moderation boolean                                                   NOT NULL,
    state              int REFERENCES publication_states (publication_state_id) NOT NULL,
    title              VARCHAR(256)                                              NOT NULL,
    views              int                                                       NOT NULL,
    PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS participations
(
    participation_id BIGINT GENERATED BY DEFAULT AS IDENTITY                  NOT NULL,
    created          TIMESTAMP WITHOUT TIME ZONE                              NOT NULL,
    event            int REFERENCES events (event_id)                         NOT NULL,
    requester        int REFERENCES users (user_id)                           NOT NULL,
    state            int REFERENCES application_states (application_state_id) NOT NULL,
    PRIMARY KEY (participation_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    pinned         boolean                                 NOT NULL,
    title          VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation BIGINT REFERENCES compilations (compilation_id) NOT NULL,
    event BIGINT REFERENCES events (event_id) NOT NULL,
    PRIMARY KEY (compilation, event)
);