CREATE TABLE IF NOT EXISTS hits
(
    hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(512) NOT NULL,
    uri varchar(512) NOT NULL,
    ip varchar(512) NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (hit_id)
);